version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "3000:3000"
  backend:
    image: "miguelfmartin89/ora-challenge:oracle-challenge-app"
    ports:
     - "8080:8080"